### ISSUE TITLE
Github登录失败

### ISSUE THREAD

**Issue by aurorataro** [dd-center/submit.vtbs.moe#5]
控制台报错403
POST https://cors-anywhere.herokuapp.com/https://github.com/login/oauth/access_token 
403 (Forbidden)

**Comment by simon300000** [comment]
啊，那暂时不要登录github

**Comment by aurorataro** [comment]
啊 没想到issue回的这么快
不过提交json保存过后，刷新页面，panel中并没有显示刚刚添加的json
请问是后台审核后显示吗？
（以为是网络错误，上传了两次）

**Comment by simon300000** [comment]
提交了的话，按钮的位置会出现一个链接的，有这样一个链接吗？

**Comment by simon300000** [comment]
好像是和这个有关 https://github.com/Rob--W/cors-anywhere/issues/301

我晚会修一修

**Comment by aurorataro** [comment]
提示保存成功。浏览器地址栏确实变动了
从<https://submit.vtbs.moe/edit> 变为<https://submit.vtbs.moe/edit/xxxxxxxxxx.json>
然后在新的标签页重新打开这个变动后的链接https://submit.vtbs.moe/edit/xxxxxxxxxx.json，显示出来的是空白页。

**Comment by aurorataro** [comment]
好的 那我先close了

**Comment by simon300000** [comment]
别close啊，不然我忘了

**Comment by aurorataro** [comment]
233333333

**Comment by simon300000** [comment]
这个只是本地的一个文件状态变化，而且只有当前窗口，要从这里上传改动
<img width="79" alt="image" src="https://user-images.githubusercontent.com/12656264/107885153-9e03da80-6f33-11eb-86ce-bc41ad154ef1.png">

**Comment by aurorataro** [comment]
奥奥   半夜眼瞎了 啥都没看到  见谅🤣

**Comment by simon300000** [comment]
理论上应该修好了

**Comment by simon300000** [comment]
试试看能不能登陆？
